# Staging environment values override
namespace: demo-orders-zappy

# Image configuration
image:
  repository: ghcr.io/brakebg/demo-orders-zappy
  pullPolicy: IfNotPresent
  tag: latest

# Using 3 replicas for staging environment
replicaCount: 3

# Enable autoscaling for staging environment
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

# Enable Ingress for staging environment
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/load-balance: "round_robin"
    # Enable SSL for staging
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: "staging-orders.example.com"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: staging-orders-tls
      hosts:
        - staging-orders.example.com

# Resource requirements for staging environment
resources:
  limits:
    cpu: 800m
    memory: 1Gi
  requests:
    cpu: 400m
    memory: 512Mi

# Spring profile for staging environment
springProfile: "staging"

# Service account configuration
serviceAccount:
  create: false
  automount: false
  name: ""
