# Development environment values override
namespace: demo-orders-zappy

# Image configuration
image:
  tag: "latest"

# Service configuration
service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

# Using 1 replica for troubleshooting
replicaCount: 1

# Disable autoscaling for troubleshooting
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

# Enable Ingress for development environment
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/load-balance: "round_robin"
  hosts:
    - host: "dev-orders.example.com"
      paths:
        - path: /
          pathType: Prefix

# Resource requirements for development environment - reduced for troubleshooting
resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi


# Spring profile for development environment
springProfile: "dev"

# Service account configuration
serviceAccount:
  create: false
  automount: false
  name: ""
