apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-orders-zappy-config
  namespace: demo-orders-zappy
data:
  application.properties: |
    # Database configuration
    spring.datasource.url=jdbc:h2:mem:testdb
    spring.datasource.username=sa
    spring.datasource.password=
    spring.h2.console.enabled=true
    spring.h2.console.settings.web-allow-others=true
    
    # JPA configuration
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.defer-datasource-initialization=false
    
    # SQL initialization
    spring.sql.init.mode=always
    
    # Actuator configuration
    management.endpoints.web.exposure.include=health,info
    
    # Active profile
    spring.profiles.active=kubernetes
